name: main

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # или ваша версия Node.js

      - name: Build project
        run: npm run build
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "${{ github.sha }}" || echo "no comments"
      
      - name: Set up SSH agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/tvelvi
      
      - name: Push changes
        run: git push origin main
